["src/dmtest/vdo/compress_tests.py::test_compress"]
executables = [ "blkdiscard", "blockdev", "dmsetup", "udevadm", "vdoformat",]
targets = [ "vdo",]

["src/dmtest/vdo/creation_tests.py::test_create"]
executables = [ "blockdev", "dmsetup", "vdoformat",]
targets = [ "vdo",]

["src/dmtest/vdo/dedupe_tests.py::test_dedupe0"]
executables = [ "blockdev", "dmsetup", "udevadm", "vdoformat",]
targets = [ "vdo",]

["src/dmtest/vdo/dedupe_tests.py::test_dedupe50"]
executables = [ "blockdev", "dmsetup", "udevadm", "vdoformat",]
targets = [ "vdo",]

["src/dmtest/vdo/dedupe_tests.py::test_dedupe75"]
executables = [ "blockdev", "dmsetup", "udevadm", "vdoformat",]
targets = [ "vdo",]

["src/dmtest/vdo/dedupe_tests.py::test_dedupeWithOffsetAndRestart"]
executables = [ "blockdev", "dmsetup", "udevadm", "vdoformat",]
targets = [ "vdo",]

["src/dmtest/vdo/dedupe_tests.py::test_dedupeWithOverwrite"]
executables = [ "blockdev", "dmsetup", "vdoformat",]
targets = [ "vdo",]

["src/dmtest/vdo/full_tests.py::test_full"]
executables = [ "blkdiscard", "blockdev", "dmsetup", "fio", "udevadm", "vdoformat",]
targets = [ "linear", "vdo",]

["src/dmtest/vdo/load_failure_tests.py::test_bad_values"]
executables = [ "blockdev", "dmsetup", "vdoformat",]
targets = [ "vdo",]

["src/dmtest/vdo/load_failure_tests.py::test_corrupt_geometry"]
executables = [ "blockdev", "dd", "dmsetup", "vdoformat",]
targets = [ "vdo",]

["src/dmtest/blk_archive/unit_tests.py::test_src_dest_combinations"]
executables = [ "blk-archive", "blockdev", "dd", "dmsetup", "losetup", "thin_check",]
targets = [ "linear", "thin", "thin-pool",]

["src/dmtest/bufio/bufio_tests.py::test_create"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_empty_program"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_new_buf"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_stamper"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_many_stampers"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_writeback_nothing"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_writes_hit_disk_sync"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_writes_hit_disk_async"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_writeback_many"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_hotspots"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_hotspots2"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/bufio/bufio_tests.py::test_multiple_caches"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test", "linear",]

["src/dmtest/bufio/bufio_tests.py::test_evict_old"]
executables = [ "blockdev", "dmsetup",]
targets = [ "bufio_test",]

["src/dmtest/cache/resize_origin_tests.py::test_expand_origin_with_reload"]
executables = [ "blockdev", "cache_check", "cache_dump", "cache_restore", "dmsetup",]
targets = [ "cache", "linear",]

["src/dmtest/cache/resize_origin_tests.py::test_shrink_origin_with_reload_drops_mappings"]
executables = [ "blockdev", "cache_check", "cache_dump", "cache_restore", "dmsetup",]
targets = [ "cache", "linear",]

["src/dmtest/cache/resize_origin_tests.py::test_shrink_origin_with_teardown_drops_mappings"]
executables = [ "blockdev", "cache_check", "cache_dump", "cache_restore", "dmsetup",]
targets = [ "cache", "linear",]

["src/dmtest/cache/resize_origin_tests.py::test_shrink_origin_with_reload_should_fail_if_blocks_dirty"]
executables = [ "blockdev", "cache_check", "cache_restore", "dmsetup",]
targets = [ "cache", "linear",]

["src/dmtest/cache/resize_origin_tests.py::test_shrink_origin_with_teardown_should_fail_if_blocks_dirty"]
executables = [ "blockdev", "cache_check", "cache_restore", "dmsetup",]
targets = [ "cache", "linear",]

["src/dmtest/cache/small_config_tests.py::test_small_config"]
executables = [ "blockdev", "cache_check", "dd", "dmsetup",]
targets = [ "cache", "linear",]

["src/dmtest/thin/creation_tests.py::test_create_lots_of_empty_thins"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_create_lots_of_empty_snaps"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_create_lots_of_recursive_snaps"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_activate_thin_while_pool_suspended_fails"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin", "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_huge_block_size"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin", "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_non_power_of_2_block_size_fails"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_too_small_block_size_fails"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_too_large_block_size_fails"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_largest_block_size_succeeds"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_too_large_a_thin_id_fails"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_largest_thin_id_succeeds"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin", "thin-pool",]

["src/dmtest/thin/creation_tests.py::test_too_small_a_metadata_dev_fails"]
executables = [ "blockdev", "dmsetup",]
targets = [ "linear",]

["src/dmtest/thin/deletion_tests.py::test_create_delete_cycle"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/deletion_tests.py::test_create_many_delete_many"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/deletion_tests.py::test_create_delete_rolling"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/deletion_tests.py::test_delete_provisioned_thin"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin", "thin-pool",]

["src/dmtest/thin/deletion_tests.py::test_delete_unknown_id_fails"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin-pool",]

["src/dmtest/thin/deletion_tests.py::test_delete_active_id_fails"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin", "thin-pool",]

["src/dmtest/thin/deletion_tests.py::test_delete_after_out_of_space"]
executables = [ "blockdev", "dd", "dmsetup", "thin_check",]
targets = [ "thin", "thin-pool",]
